[package]
name = "fat32_reimplementation"
version = "0.1.0"
edition = "2021"
authors = ["Author Name <t.legrand@myskolae.fr>"]

[lib]
name = "fat32_reimplementation"
path = "src/libs.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[example]]
name = "commandline"
path = "exemple/commandline.rs"